### ISSUE TITLE
Update code to support jose 4.x

### ISSUE THREAD

**Issue by salievn** [curityio/express-oauth-jwt#4]
Hi Curity Team,

Any plan to update this project to support jose 4.x. It seems to change many things since de 1.25 used in current version ?
It will be great if you can update this demo project to promote this lib.

Best regards

**Comment by mtrojanowski** [comment]
Hey @salievn,

Thanks for pointing that out! I've just released version 2.0.0 of our library with jose upgraded to 4.x. It simplified the code and made some classes redundant. The change did end up being a breaking one, but I hope it will not be that much of a problem. I also added a [changelog](https://github.com/curityio/express-oauth-jwt/blob/master/CHANGELOG.md) which summarises the breaking changes.
